function default_figure_style(ax)
% DEFAULT_FIGURE_STYLE
%

    set(ax.Parent,...
        'Color','w',...
        'FontSize',20)
    set(ax,'Linewidth',2,...
        'TickDir','out',...
        'TickLength',[.02 .02],...
        'XMinorTick','on',...
        'YMinorTick','on',...
        'Xgrid','on',...
        'Ygrid','on')
end