%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\lezaack\Documents\AALASA\expérimental AALASA\traction général\métal de base T8 - 20 mm\BM_T8_155c18h_L1.xlsx
%    Worksheet: Values 2050_20mm_L1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2024/06/10 10:23:48

%% Import the data
[~, ~, raw] = xlsread('C:\Users\lezaack\Documents\AALASA\expérimental AALASA\traction général\métal de base T8 - 20 mm\BM_T8_155c18h_L1.xlsx','Values 2050_20mm_L1','A4:D11359');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Time = data(:,1);
Standardforce = data(:,2);
Griptogripseparation = data(:,3);
Standardtravel = data(:,4);

%% Clear temporary variables
clearvars data raw R;


COLOR = [0, 0, 1];
A0 = pi*(5.94/2)^2*10^-6; %%CHECK
l0 = 30; %%CHECK
ARG = 7000;
OFF = 150;
plotFun();